# Generated by Django 5.1.7 on 2025-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_duration_movieprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Video duration in seconds', null=True),
        ),
    ]
