# Generated by Django 5.1.7 on 2025-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_120p',
            field=models.FileField(blank=True, null=True, upload_to='videos/120p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
    ]
