# Generated by Django 5.1.7 on 2025-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieprogress',
            name='progress',
            field=models.CharField(default='0%', max_length=10),
        ),
    ]
