# Generated by Django 5.1.7 on 2025-03-29 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_video_1080p_movie_video_120p_movie_video_360p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='conversion_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
