# Generated by Django 5.1.7 on 2025-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieprogress_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
