# Generated by Django 5.1.7 on 2025-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_category_movie_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_120p',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
