# Generated by Django 5.1.7 on 2025-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieprogress_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieprogress',
            name='progress',
        ),
    ]
