# Generated by Django 5.1.7 on 2025-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movieprogress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional. Wenn du keinen Thumbnail hochlädst, wird automatisch einer erzeugt.', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, help_text='Optional. Wenn du keinen Trailer hochlädst, wird automatisch einer erzeugt.', null=True, upload_to='trailers/'),
        ),
    ]
