# Generated by Django 5.1.7 on 2025-04-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_thumbnail_alter_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='Das Original-Video wird automatisch in verschiedene Auflösungen konvertiert und anschließend gelöscht.', null=True, upload_to='videos/'),
        ),
    ]
